### PR TITLE
Some cleanup and adjustment for Rust 1.24.1 compatibility

### PR DESCRIPTION
**Pull request by stratact**

### CODE REVIEW

**Comment by stratact** [comment]
Is that all you need?

**Comment by euank** [comment]
Yup, looks good, thanks! I assume you'll also want a `0.1.1` release that includes this. I should be able to get to that tomorrow.

Once there's a release with these changes, it'll be possible for you to pin to it as well, so future compatibility with 1.24.1 will matter a bit less.. Though I guess I also don't expect there'll be many changes or reason to break compiler compatibility, so we'll see I guess.

**Comment by stratact** [comment]
Yep, I would appreciate a `0.1.1` release. This [crate](https://github.com/pop-os/envfile) depends on yours, which a project I'm writing on depends on top of that, but my friends need to make sure that crate builds on `1.24.1`, or at least until that's not a concern in the future.

**Comment by mmstick** [comment]
> I don't mind keeping compatibility with some older rust versions

Thanks. Software being packaged for Ubuntu / Pop!\_OS 18.04 must be able compile with 1.24.1, since that the version we're stuck with on that platform.

**Comment by euank** [comment]
I've released v0.1.1 with this change (and some cosmetic documentation updates).

As a heads up, I'll also be publishing a v0.2.0 quite soon (probably today) because I realized escape doesn't produce as readable strings as I meant it to in some cases (see https://github.com/euank/snailquote/pull/4).

**Comment by stratact** [comment]
Thanks for all of your work @euank :smile_cat:

**Pull request merged**
